
export const ListProfession = [
  "Band",
  "DJ",
  "Soloist",
  "Acappella",
  "Choir",
  "Musician",
  "A&R Administrator",
  "A&R Coordinator",
  "Accompanist",
  "Arranger",
  "Audio Manufacturer",
  "AV Rental Company",
  "Background Singer",
  "Band Director",
  "Bar",
  "Booking Agent",
  "Business Manager",
  "Catering Company",
  "CD Manufacturer",
  "Choreographer",
  "Club",
  "Club Manager",
  "College, Conservatory, or University Music Teacher",
  "Composer",
  "Concert / Event Venue",
  "Concert Hall Manager",
  "Concert Promoter",
  "Cruise Ship Musician",
  "Dance / Cover Band",
  "DJ School",
  "Emcee / Host",
  "Entertainment Attorney",
  "Ethnomusicologist",
  "Event Manager",
  "Festival Promoter",
  "FOH Engineer",
  "Guitar Tech",
  "Instrument Repair & Restoration Specialist",
  "Instrument Sales Representative",
  "Jam Studio",
  "Jingle Writer",
  "Keyboard Tech",
  "LED Wall Company",
  "Licensing Representative",
  "Lighting Designer",
  "Lighting Manufacturer",
  "Lyricist",
  "Mastering Company",
  "Merchandise Company",
  "Mix Engineer",
  "Monitor Engineer",
  "Music Blogger",
  "Music Business Accountant",
  "Music Critic",
  "Music Director (MD)",
  "Music Historian",
  "Music Instruments Company",
  "Music Journalist",
  "Music Librarian",
  "Music Photographer",
  "Music Producer",
  "Music Publisher",
  "Music School",
  "Music Software",
  "Music Store Manager",
  "Music Store Salesperson",
  "Music Teacher",
  "Music Video Producer",
  "Music Videographer",
  "Music Website",
  "Musical Instrument Builder / Designer",
  "Musical Instruments Shop",
  "Musicologist",
  "Orchestra",
  "Orchestrator",
  "Personal Manager",
  "Piano Tuner-Technician",
  "Private Instrument Teacher",
  "Production Music Writer",
  "Professional Manager",
  "Program Director (PD)",
  "Pub",
  "Publicist",
  "Radio DJ",
  "Radio Station",
  "Record & CD Store",
  "Record Label",
  "Record Producer",
  "Record Store Manager",
  "Recording Artist Personal Assistant",
  "Recording Assistant",
  "Recording Engineer",
  "Recording Studio Manager",
  "Rigger",
  "Roadie",
  "Session Musician",
  "Session Singer",
  "Show Band",
  "Singer",
  "Songwriter",
  "Sound Designer",
  "Sound Engineer",
  "Sound Technician",
  "Stage Manager",
  "Staging Company",
  "Talent Agency",
  "Talent Buyer",
  "Ticketing Company",
  "Tour Manager",
  "Video Company",
  "Video Game Composer",
  "Video Jockey (VJ)",
  "Vinyl Manufacturer",
  "Voice Coach",
  "Voiceover Artist"
];
